Update mimoto-oidc-policy.json
mosip/mosip-onboarding pull request #71
Opened 2023-12-01 12:05 UTC by Mahesh-Binayak

2023-12-01 12:08 UTC, syedsalman3753 requested changes
Update default.sh from develop branch

And Please after esignet vc release

2024-01-19 11:51 UTC, syedsalman3753 approved these changes

2024-01-19 11:56 UTC, syedsalman3753 approved these changes

2024-01-19 12:15 UTC, Prafulrakhade approved these changes

2024-01-22 06:10 UTC, ckm007 approved these changes

2024-01-22 06:10 UTC, merged